version: '2'
services:
  db:
    container_name: perlmvc-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-datavolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    container_name: perlmvc-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8183:80
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    links:
    - db
volumes:
  mysql-datavolume: